"""Add content_details to sites table

Revision ID: 35c3064ba287
Revises: db1e70e87c1b
Create Date: 2025-06-30 16:48:57.133792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c3064ba287'
down_revision: Union[str, None] = 'db1e70e87c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('sites', sa.Column('content_details', sa.JSON(), nullable=True))
    
    # Update existing records with default content_details
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE sites 
        SET content_details = '{
            "event_title": "' || title || '",
            "description": "Детали события",
            "contact_name": "",
            "contact_email": "",
            "contact_phone": ""
        }'::json
        WHERE content_details IS NULL
    """))
    
    # Now make the column NOT NULL
    op.alter_column('sites', 'content_details', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'content_details')
    # ### end Alembic commands ###
