name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd Qonaq-Invite
            git remote set-url origin git@github.com:shadowpr1est/Qonaq-Invite.git
            git pull origin main
            docker-compose pull
            docker-compose up --build -d
            docker-compose exec -T backend alembic upgrade head
